In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mlt
import seaborn as sns
import tensorflow as tf
df=pd.read_csv('Automobile.csv')
df

,Customer ID,Age,Income_Bucket,Gender,State,Region,Marital_Status,No_of_children,Occupation,Vehicle_Segment,No_of_months,Hobbies,On_Call_Offer
0,46756841,28,2,M,Q,Sub-urban#,1,4,White Collar Clerical,SUV,39,Swimming,Plan 1
1,48408855,25,3,M,A,Sub-urban#,2,3,Engineer,Compact SUV,14,Painting,Plan 5
2,23645631,58,2,M,Z,Urban#,2,4,Defence,Car,24,Reading Books,Plan 5
3,65645152,37,1,M,W,Sub-urban#,2,4,Sales Executive,Pick up truck,27,Gourmet Cooking,Plan 4
4,52236057,64,2,M,S,Sub-urban,1,4,Chef,Pick up truck,56,Music,Plan 4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10728,93533721,57,2,F,V,Urban,2,2,White Collar Clerical,Car,9,Painting,Plan 5
10729,46199596,31,1,F,B,Urban,1,2,White Collar Clerical,Car,44,Painting,Plan 5
10730,71833901,29,1,F,N,Urban,1,0,White Collar Clerical,Car,40,Painting,Plan 5
10731,22935366,20,1,F,M,Urban,1,3,White Collar Clerical,Car,59,Painting,Plan 5
10732,58840492,24,1,F,M,Urban,1,2,White Collar Clerical,Car,25,Painting,Plan 5

In [42]:
df.dtypes

Customer ID         int64
Age                 int64
Income_Bucket       int64
Gender             object
State              object
Region             object
Marital_Status      int64
No_of_children      int64
Occupation         object
Vehicle_Segment    object
No_of_months        int64
Hobbies            object
On_Call_Offer      object
dtype: object

In [43]:
df.isna().sum()

Customer ID         0
Age                 0
Income_Bucket       0
Gender              0
State              18
Region              0
Marital_Status      0
No_of_children      0
Occupation          0
Vehicle_Segment     0
No_of_months        0
Hobbies             0
On_Call_Offer       0
dtype: int64

In [44]:
df['Occupation'].unique()

array(['White Collar Clerical', 'Engineer', 'Defence', 'Sales Executive',
       'Chef', 'Investment Banker', 'Orthopeadic', 'Gardener',
       'Interior designer', 'Architect', 'Research Analyst',
       'Wildlife Photographer', 'Writer', 'Marketing Analyst', 'Designer',
       'Web App Developer', 'Professor', 'Actor'], dtype=object)

In [45]:
df.drop(['State','Gender','Customer ID','Age','Gender','Hobbies'],axis=1,inplace=True)

In [46]:
df.dtypes

Income_Bucket       int64
Region             object
Marital_Status      int64
No_of_children      int64
Occupation         object
Vehicle_Segment    object
No_of_months        int64
On_Call_Offer      object
dtype: object

In [47]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Region']=lab.fit_transform(df['Region'])
df['Occupation']=lab.fit_transform(df['Occupation'])
df['Vehicle_Segment']=lab.fit_transform(df['Vehicle_Segment'])
df['On_Call_Offer']=lab.fit_transform(df['On_Call_Offer'])

In [48]:
df.dtypes

Income_Bucket      int64
Region             int64
Marital_Status     int64
No_of_children     int64
Occupation         int64
Vehicle_Segment    int64
No_of_months       int64
On_Call_Offer      int64
dtype: object

In [49]:
df.isna().sum()

Income_Bucket      0
Region             0
Marital_Status     0
No_of_children     0
Occupation         0
Vehicle_Segment    0
No_of_months       0
On_Call_Offer      0
dtype: int64

In [50]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [51]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 1,  0,  1, ...,  2,  3, 35],
       [ 1,  1,  2, ..., 13,  2, 22],
       [ 1,  1,  2, ..., 10,  2, 13],
       ...,
       [ 2,  4,  1, ..., 14,  2, 23],
       [ 1,  1,  2, ..., 13,  3,  7],
       [ 1,  1,  1, ..., 12,  0, 52]], shape=(7513, 7))

In [52]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [53]:
from keras.models import Sequential
from keras.layers import Dense

In [54]:
df['On_Call_Offer'].unique()

array([0, 4, 3, 1, 2])

In [55]:
ann=Sequential()
ann.add(Dense(7,activation='relu'))
ann.add(Dense(10,activation='relu'))
ann.add(Dense(10,activation='relu'))
ann.add(Dense(5,activation='softmax'))

In [56]:
ann.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])
ann.fit(x_train,y_train,epochs=100,batch_size=200)

Epoch 1/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.2642 - loss: 1.6655
Epoch 2/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5005 - loss: 1.4203
Epoch 3/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5944 - loss: 1.2473
Epoch 4/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6046 - loss: 1.1554
Epoch 5/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6046 - loss: 1.1132
Epoch 6/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6046 - loss: 1.0889
Epoch 7/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6046 - loss: 1.0651
Epoch 8/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6046 - loss: 1.0354
Epoch 9/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6044 - loss: 0.9960
Epoch 10/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6081 - loss: 0.9425
Epoch 11/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6973 - loss: 0.8762
Epoch 12/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7761 - loss: 0.7948
Epoch 13/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8163 - loss: 0.6971
Epoch 14/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8403 - loss: 0.5908
Epoch 15/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8578 - loss: 0.4942
Epoch 16/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8676 - loss: 0.4188
Epoch 17/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8724 - loss: 0.3598
Epoch 18/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8823 - loss: 0.3103
Epoch 19/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9324 - loss: 0.2687
Epoch 20/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9476 - loss: 0.2322
Epoch 21/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9550 - loss: 0.2001
Epoch 22/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9609 - loss: 0.1713
Epoch 23/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9639 - loss: 0.1484
Epoch 24/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9686 - loss: 0.1289
Epoch 25/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9728 - loss: 0.1125
Epoch 26/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9756 - loss: 0.0978
Epoch 27/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9763 - loss: 0.0856
Epoch 28/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9790 - loss: 0.0742
Epoch 29/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9832 - loss: 0.0637
Epoch 30/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9907 - loss: 0.0545
Epoch 31/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9964 - loss: 0.0469
Epoch 32/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9977 - loss: 0.0401
Epoch 33/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0344
Epoch 34/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9992 - loss: 0.0299
Epoch 35/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0259
Epoch 36/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0226
Epoch 37/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0200
Epoch 38/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0179
Epoch 39/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0160
Epoch 40/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0145
Epoch 41/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0132
Epoch 42/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0121
Epoch 43/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0112
Epoch 44/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0104
Epoch 45/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0097
Epoch 46/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0091
Epoch 47/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0085
Epoch 48/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0080
Epoch 49/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0076
Epoch 50/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0073
Epoch 51/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0069
Epoch 52/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0066
Epoch 53/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0063
Epoch 54/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0061
Epoch 55/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0058
Epoch 56/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0056
Epoch 57/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0053
Epoch 58/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0052
Epoch 59/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0050
Epoch 60/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0049
Epoch 61/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0047
Epoch 62/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0046
Epoch 63/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0044
Epoch 64/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0042
Epoch 65/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0042
Epoch 66/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0040
Epoch 67/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0039
Epoch 68/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0038
Epoch 69/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0037
Epoch 70/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0036
Epoch 71/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0035
Epoch 72/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0034
Epoch 73/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0033
Epoch 74/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0032
Epoch 75/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0031
Epoch 76/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0031
Epoch 77/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0030
Epoch 78/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0030
Epoch 79/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0028
Epoch 80/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0028
Epoch 81/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0027
Epoch 82/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0026
Epoch 83/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0026
Epoch 84/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0025
Epoch 85/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0025
Epoch 86/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0024
Epoch 87/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0023
Epoch 88/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9997 - loss: 0.0023
Epoch 89/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0022
Epoch 90/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0022
Epoch 91/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0021
Epoch 92/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0021
Epoch 93/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0021
Epoch 94/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0020
Epoch 95/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0019
Epoch 96/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0019
Epoch 97/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0018
Epoch 98/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0018
Epoch 99/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0018
Epoch 100/100
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9999 - loss: 0.0017

In [57]:
ann.evaluate(x_test,y_test)

101/101 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9988 - loss: 0.0067

[0.006696725729852915, 0.9987577795982361]

In [58]:
df

,Income_Bucket,Region,Marital_Status,No_of_children,Occupation,Vehicle_Segment,No_of_months,On_Call_Offer
0,2,2,1,4,15,3,39,0
1,3,2,2,3,5,1,14,4
2,2,5,2,4,3,0,24,4
3,1,2,2,4,13,2,27,3
4,2,1,1,4,2,2,56,3
...,...,...,...,...,...,...,...,...
10728,2,4,2,2,15,0,9,4
10729,1,4,1,2,15,0,44,4
10730,1,4,1,0,15,0,40,4
10731,1,4,1,3,15,0,59,4
10732,1,4,1,2,15,0,25,4

In [59]:
y_pred=ann.predict(scaler.transform([[3,'Urban',1,4,2,'Chef','Compact SUV',56]]))

ValueError: could not convert string to float: 'Urban'